# Generated by Django 5.1.6 on 2025-02-23 14:14

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_airplane_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='image',
            field=models.ImageField(null=True, upload_to=airport.models.airplane_image_path),
        ),
    ]
